feat: add /get to redirect to store
PapillonApp/getpapillon-svelte pull request #4
Opened 2024-03-28 09:59 UTC by godetremy

2024-03-28 17:22 UTC, Ahhj93 approved these changes

2024-03-28 17:28 UTC, Ahhj93 requested changes

2024-03-28 17:28 UTC, Ahhj93 commented on src/routes/get/+page.svelte
> +				Prépare toi à découvrir une révolution !
```suggestion
				Prépare-toi à découvrir une révolution !
```

2024-03-28 17:28 UTC, Ahhj93 commented on src/routes/get/+page.svelte
> +				Nous préparons ton arrivé(e), tu vas bientôt pouvoir télécharger Papillon.
```suggestion
				Nous préparons ton arrivée, tu vas bientôt pouvoir télécharger Papillon.
```

"arrivée" toujours au féminin c'est un nom

2024-03-28 17:28 UTC, Ahhj93 commented on src/routes/get/+page.svelte
> +				Oups, nous n'arrivons pas à derterminer ton appareil.
```suggestion
				Oups, nous n'arrivons pas à déterminer ton appareil.
```

2024-03-28 17:28 UTC, Ahhj93 commented on src/routes/get/+page.svelte
> +				Séléctionne ton appareil ci-dessous pour télécharger Papillon.
```suggestion
				Sélectionne ton appareil ci-dessous pour télécharger Papillon.
```

2024-03-28 17:54 UTC, Ahhj93 approved these changes

2024-03-28 17:59 UTC, Vilerio commented
Une implémentation des mêmes stats qu'avec OneLink serait pas mal je pense, je ne review donc pas positivement pour le moment, j'attend la review de @ecnivtwelve 

Sinon bon travail !

2024-03-28 18:26 UTC, godetremy commented
> Une implémentation des mêmes stats qu'avec OneLink serait pas mal je pense, je ne review donc pas positivement pour le moment, j'attend la review de @ecnivtwelve 
> 
> 
> 
> Sinon bon travail !

Elle arrivera prochainement (notamment à cause de l'hébergement qui ne peux contenir de code serveur), hors si le liens est valide rapidement je pourrais commencer à voir à la publicité, ainsi qu'à l'intégration dans Papillon

2024-04-12 21:42 UTC, Vilerio requested changes
Je pense qu'il faut vraiment ces statistiques, mais @ecnivtwelve t'en penses quoi ?
Par contre là ou je suis d'accord avec toi Rémy, c'est sur un lien en getpapillon pour download, mais normalement on peut rediriger vers le onelink

2024-04-13 09:49 UTC, godetremy commented
> Je pense qu'il faut vraiment ces statistiques, mais @ecnivtwelve t'en penses quoi ? Par contre là ou je suis d'accord avec toi Rémy, c'est sur un lien en getpapillon pour download, mais normalement on peut rediriger vers le onelink

On pourrait faire une redirection avec le domaine dans ce cas ! Beaucoup plus simple à faire !

2024-04-13 09:51 UTC, Vilerio commented
> > Je pense qu'il faut vraiment ces statistiques, mais @ecnivtwelve t'en penses quoi ? Par contre là ou je suis d'accord avec toi Rémy, c'est sur un lien en getpapillon pour download, mais normalement on peut rediriger vers le onelink
> 
> On pourrait faire une redirection avec le domaine dans ce cas ! Beaucoup plus simple à faire !

oui, c'est ce dont je parlais

2024-04-24 18:13 UTC, closed without merging